insert into vendor (vendor_id,  vendor_name,  delivery_charge,rating) values (1, 'Amazon', 30.5, 5.0 );
insert into vendor (vendor_id,  vendor_name,  delivery_charge,rating) values (2, 'Flipkart', 40.5, 4.0 );
insert into vendor (vendor_id,  vendor_name,  delivery_charge,rating) values (3, 'JioMart', 25.5, 4.2 );
insert into vendorstock (expected_stock_replinshment_date, stock_in_hand, vendor_id, product_id, id) values ('2021-07-13', 150, 1, 1, 1);
insert into vendorstock (expected_stock_replinshment_date, stock_in_hand, vendor_id, product_id, id) values ('2021-07-13', 300, 2, 1, 6);
insert into vendorstock (expected_stock_replinshment_date, stock_in_hand, vendor_id, product_id, id) values ('2021-07-13', 140, 2, 2, 2);
insert into vendorstock (expected_stock_replinshment_date, stock_in_hand, vendor_id, product_id, id) values ('2021-07-16', 120, 3, 1, 3);
insert into vendorstock (expected_stock_replinshment_date, stock_in_hand, vendor_id, product_id, id) values ('2021-08-01', 50, 1, 3, 4);
insert into vendorstock (expected_stock_replinshment_date, stock_in_hand, vendor_id, product_id, id) values ('2021-08-01', 40, 2, 4, 5);
insert into vendorstock (expected_stock_replinshment_date, stock_in_hand, vendor_id, product_id, id) values ('2021-08-01', 100, 2, 5, 7);
insert into vendorstock (expected_stock_replinshment_date, stock_in_hand, vendor_id, product_id, id) values ('2021-08-01', 200, 1, 6, 8);
insert into vendorstock (expected_stock_replinshment_date, stock_in_hand, vendor_id, product_id, id) values ('2021-08-01', 0, 2, 7, 9);
insert into vendorstock (expected_stock_replinshment_date, stock_in_hand, vendor_id, product_id, id) values ('2021-08-01', 240, 1, 8, 10);