eureka:
 instance:
  hostname: localhost
  prefer-ip-address: true
  lease-expiration-duration-in-seconds: 20
  lease-renewal-interval-in-seconds: 10
 client:
  register-With-Eureka: true
  fetch-Registry: true
  service-Url:
   defaultZone: "http://localhost:8761/eureka/" 